CREATE TABLE couriers
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                VARCHAR(100) NOT NULL,
    phone               VARCHAR(30) NOT NULL UNIQUE,
    status              VARCHAR(30) NOT NULL,
    current_delivery_id BIGINT,
    created_at          TIMESTAMP NOT NULL,
    updated_at          TIMESTAMP NOT NULL
);
