spring:
  application:
    name: auth-service

  datasource:
    url: jdbc:postgresql://localhost:5432/delivery_auth
    username: postgres
    password: "${DB_PASSWORD}"

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

  flyway:
    enabled: true

server:
  port: 8083

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

  endpoint:
    health:
      show-details: always

jwt:
  secret: "${JWT_SECRET}"
  expiration-seconds: 3600