CREATE TABLE deliveries
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_name    VARCHAR(100) NOT NULL,
    customer_phone   VARCHAR(30) NOT NULL,
    pickup_address   VARCHAR(300) NOT NULL,
    delivery_address VARCHAR(300) NOT NULL,
    status           VARCHAR(30) NOT NULL,
    courier_id       BIGINT,
    created_at       TIMESTAMP NOT NULL,
    updated_at       TIMESTAMP NOT NULL
);
