CREATE TABLE notifications
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id    UUID NOT NULL UNIQUE,
    delivery_id BIGINT NOT NULL,
    type        VARCHAR(30) NOT NULL,
    message     VARCHAR(500) NOT NULL,
    is_read     BOOLEAN NOT NULL,
    created_at  TIMESTAMP NOT NULL
);
